<a href="https://colab.research.google.com/github/GilangAngga12/Pemrosesan-teks-praktik/blob/main/Datatugas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preprocessing Teks

In [1]:
 %pip install polars nltk Sastrawi

Requirement already satisfied: polars in /usr/local/lib/python3.13/dist-packages (1.35.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (3.9.1)
Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.13/dist-packages (from polars) (1.35.2)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from nltk) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib->nltk) (3.1.2)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 7.9 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

## Library

In [2]:
import re
import html
import polars as pl
import nltk
# import spacy
import unicodedata
from functools import lru_cache
from collections import Counter

# import pandas as pd

from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [3]:
nltk.download("stopwords")

# Model spaCy untuk bahasa Indonesia
# spacy.cli.download("xx_ent_wiki_sm")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

## Helper Fungsion

In [4]:
def to_list(v):
    """map_elements memberi pl.Series untuk kolom list -> ubah ke list Python."""
    if v is None: return []
    if isinstance(v, pl.Series): return v.to_list()
    return list(v)

def _apply_str(df, col, out, fn):
    return df.with_columns(pl.col(col).map_elements(fn, return_dtype=pl.Utf8).alias(out))

def _apply_list(df, col, out, fn):
    return df.with_columns(
        pl.col(col).map_elements(lambda v: fn(to_list(v)), return_dtype=pl.List(pl.Utf8)).alias(out))

## Dataset

In [8]:
df = pl.read_csv("/content/Bagi DOC-20261018-WA0016.csv")

In [9]:
df

shape: (200, 13)
┌───────────┬───────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬──────────┐
│ aplikasi  ┆ tahun ┆ reviewId   ┆ userName   ┆ … ┆ reviewCrea ┆ replyConte ┆ repliedAt ┆ relevant │
│ ---       ┆ ---   ┆ ---        ┆ ---        ┆   ┆ tedVersion ┆ nt         ┆ ---       ┆ ---      │
│ str       ┆ i64   ┆ str        ┆ str        ┆   ┆ ---        ┆ ---        ┆ str       ┆ bool     │
│           ┆       ┆            ┆            ┆   ┆ str        ┆ str        ┆           ┆          │
╞═══════════╪═══════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪══════════╡
│ cakap     ┆ 2021  ┆ d66cbb5a-5 ┆ Budi       ┆ … ┆ 3.4.3      ┆ Terimakasi ┆ 2021-03-0 ┆ null     │
│           ┆       ┆ 899-4e4e-8 ┆ Ariansyah  ┆   ┆            ┆ h atas     ┆ 6         ┆          │
│           ┆       ┆ f3b-6c0e0c ┆            ┆   ┆            ┆ dukungan   ┆ 14:57:56  ┆          │
│           ┆       ┆ …          ┆            ┆   ┆            ┆ kaka…      ┆           ┆          │
│ ruangguru ┆ 2024  ┆ 9103da38-6 ┆ Finixsa    ┆ … ┆ 6.93.0     ┆ Makasih ya ┆ 2024-12-2 ┆ true     │
│           ┆       ┆ 1a9-417a-b ┆ Salsa      ┆   ┆            ┆ udah kasih ┆ 7         ┆          │
│           ┆       ┆ 607-dc4aea ┆            ┆   ┆            ┆ kepercay…  ┆ 12:39:09  ┆          │
│           ┆       ┆ …          ┆            ┆   ┆            ┆            ┆           ┆          │
│ ruangguru ┆ 2020  ┆ ce22bae3-c ┆ IKhwan617  ┆ … ┆ 6.1.1      ┆ Hai,       ┆ 2020-11-2 ┆ true     │
│           ┆       ┆ 575-4fd3-b ┆            ┆   ┆            ┆ terima     ┆ 8         ┆          │
│           ┆       ┆ aa0-2eea35 ┆            ┆   ┆            ┆ kasih atas ┆ 15:28:50  ┆          │
│           ┆       ┆ …          ┆            ┆   ┆            ┆ review …   ┆           ┆          │
│ ruangguru ┆ 2024  ┆ 4725fcfd-0 ┆ aikoo      ┆ … ┆ 6.84.0     ┆ Maaf       ┆ 2024-07-2 ┆ true     │
│           ┆       ┆ c6c-4de5-b ┆            ┆   ┆            ┆ banget     ┆ 4         ┆          │
│           ┆       ┆ a3f-77785f ┆            ┆   ┆            ┆ Aikoo      ┆ 16:27:34  ┆          │
│           ┆       ┆ …          ┆            ┆   ┆            ┆ kalau nama ┆           ┆          │
│           ┆       ┆            ┆            ┆   ┆            ┆ s…         ┆           ┆          │
│ pahamify  ┆ 2022  ┆ 471da223-1 ┆ Ghefina    ┆ … ┆ 2.0.2      ┆ Hai        ┆ 2022-01-1 ┆ true     │
│           ┆       ┆ c7f-4821-8 ┆ Dinda      ┆   ┆            ┆ Ghefina,   ┆ 8         ┆          │
│           ┆       ┆ 4e6-7889b2 ┆ Fauziah    ┆   ┆            ┆ mohon maaf ┆ 11:30:40  ┆          │
│           ┆       ┆ …          ┆            ┆   ┆            ┆ atas k…    ┆           ┆          │
│ …         ┆ …     ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …        │
│ ruangguru ┆ 2021  ┆ 1c210ab7-f ┆ Firda      ┆ … ┆ 6.24.3     ┆ Hai Firda, ┆ 2021-10-1 ┆ true     │
│           ┆       ┆ 8cb-4f32-8 ┆ Khaerani   ┆   ┆            ┆ terima     ┆ 1         ┆          │
│           ┆       ┆ 148-f0f315 ┆            ┆   ┆            ┆ kasih      ┆ 12:35:35  ┆          │
│           ┆       ┆ …          ┆            ┆   ┆            ┆ sudah …    ┆           ┆          │
│ cakap     ┆ 2021  ┆ 6a9e2125-e ┆ Agung      ┆ … ┆ 3.7.4      ┆ null       ┆ null      ┆ null     │
│           ┆       ┆ 180-4b48-9 ┆ Setiawan   ┆   ┆            ┆            ┆           ┆          │
│           ┆       ┆ dd8-69efd8 ┆            ┆   ┆            ┆            ┆           ┆          │
│           ┆       ┆ …          ┆            ┆   ┆            ┆            ┆           ┆          │
│ cakap     ┆ 2022  ┆ 44baab89-c ┆ Eka Novi   ┆ … ┆ 3.9.0      ┆ Terima     ┆ 2022-04-0 ┆ null     │
│           ┆       ┆ 59a-458b-8 ┆            ┆   ┆            ┆ kasih atas ┆ 6         ┆          │
│           ┆       ┆ 465-2d22eb ┆            ┆   ┆            ┆ ulasan     ┆ 10:53:36  ┆          │
│           ┆       ┆ …          ┆            ┆   ┆            ┆ Kakak…     ┆           ┆          │
│ cakap     ┆ 2020  ┆ 2b6cab67-e ┆ sagy       ┆ … ┆ 3.3.1      ┆ null       ┆ null      ┆ null     │
│           ┆       ┆ 7a3-40ee-b ┆ Martha     ┆   ┆            ┆            ┆           ┆          │
│           ┆       ┆ 44d-5f6644 ┆            ┆   ┆            ┆            ┆           ┆          │
│           ┆       ┆ …          ┆            ┆   ┆            ┆            ┆           ┆          │
│ cakap     ┆ 2021  ┆ ca7b584d-b ┆ Nadhif     ┆ … ┆ null       ┆ null       ┆ null      ┆ null     │
│           ┆       ┆ a7c-4d64-9 ┆ Hidayat    ┆   ┆            ┆            ┆           ┆          │
│           ┆       ┆ 122-532ab6 ┆            ┆   ┆            ┆            ┆           ┆          │
│           ┆       ┆ …          ┆            ┆   ┆            ┆            ┆           ┆          │
└───────────┴───────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴──────────┘

In [ ]:
df.dtypes

[String]

In [15]:
# Muat ulang data asli agar kolom 'content' kembali tersedia
df = pl.read_csv("/content/Bagi DOC-20261018-WA0016.csv")

# Pilih kolom 'content' dan ubah namanya menjadi 'text'
df = df.select(pl.col("content").alias("text"))
df

shape: (200, 1)
┌─────────────────────────────────┐
│ text                            │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Aplikasi cerdas ,cepat dan sim… │
│ aplikasi ruang guru sangat mem… │
│ aplikasi nya jelek tapi booong… │
│ sebenarnya baru juga download … │
│ baguss sih buat belajar, mudah… │
│ …                               │
│ bagus aplikasinya, banyak lati… │
│ hallo saya Agung Setiawan dari… │
│ Bikin belajar bahasa inggris m… │
│ Mohon dipermudahkan untuk masu… │
│ Thank you for the test... Pela… │
└─────────────────────────────────┘

## Noise Removal

Noise Removal digunakan untuk membersihkan atau menghapus elemen yang biasanya tidak dibutuhkan dalam analisis teks, seperti HTML, URL, alamat email, mention, karakter kontrol, dan spasi berlebih yang tidak relevan dan tidak memiliki nilai informasi untuk analisis teks.

Contoh yang dibersihkan: Tanda baca, emoji, tag HTML, URL, karakter khusus (seperti @, #, $), dan spasi berlebih (whitespace).

### Code

In [16]:
EMOJI = re.compile("[\U0001F300-\U0001FAFF\U00002600-\U000027BF\U0001F1E6-\U0001F1FF\uFE0F\u200d]")

In [17]:
def noise_removal(df, text_col, output_col="text_clean"):
    def clean(text):
        if text is None: return ""
        text = html.unescape(str(text))
        text = re.sub(r"<[^>]+>", " ", text)
        text = re.sub(r"https?://\S+|www\.\S+|\b\w+\.(?:co|com|id)/\S+", " ", text)
        text = re.sub(r"\b[\w.+-]+@[\w.-]+\.[a-zA-Z]{2,}\b", " ", text)
        text = re.sub(r"(?<!\w)@\w+", " ", text)
        text = re.sub(r"^\s*RT\b", " ", text)
        # hashtag: buang '#', pisahkan CamelCase
        text = re.sub(r"#(\w+)", lambda m: " " + re.sub(r"(?<=[a-z])(?=[A-Z])", " ", m.group(1)) + " ", text)
        text = EMOJI.sub(" ", text)
        text = re.sub(r"[\x00-\x1f\x7f]", " ", text)
        return re.sub(r"\s+", " ", text).strip()
    return _apply_str(df, text_col, output_col, clean)

ROMAN = re.compile(r"^m{0,3}(cm|cd|d?c{0,3})(xc|xl|l?x{0,3})(ix|iv|v?i{0,3})$")
def _collapse(m):
    w = m.group(0)
    if ROMAN.match(w) or w == "www":      # III, XXX, www jangan diubah
        return w
    return re.sub(r"(\w)\1{2,}", r"\1", w)

In [18]:
df_noise = noise_removal(
    df, text_col="text"
)

In [19]:
df_noise

shape: (200, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ text                            ┆ text_clean                      │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ Aplikasi cerdas ,cepat dan sim… ┆ Aplikasi cerdas ,cepat dan sim… │
│ aplikasi ruang guru sangat mem… ┆ aplikasi ruang guru sangat mem… │
│ aplikasi nya jelek tapi booong… ┆ aplikasi nya jelek tapi booong… │
│ sebenarnya baru juga download … ┆ sebenarnya baru juga download … │
│ baguss sih buat belajar, mudah… ┆ baguss sih buat belajar, mudah… │
│ …                               ┆ …                               │
│ bagus aplikasinya, banyak lati… ┆ bagus aplikasinya, banyak lati… │
│ hallo saya Agung Setiawan dari… ┆ hallo saya Agung Setiawan dari… │
│ Bikin belajar bahasa inggris m… ┆ Bikin belajar bahasa inggris m… │
│ Mohon dipermudahkan untuk masu… ┆ Mohon dipermudahkan untuk masu… │
│ Thank you for the test... Pela… ┆ Thank you for the test... Pela… │
└─────────────────────────────────┴─────────────────────────────────┘

In [20]:
print(type(df))

<class 'polars.dataframe.frame.DataFrame'>

## Normalisasi Teks

Normalisasi teks adalah proses menyeragamkan format teks, terutama huruf kapital, Unicode, dan spasi agar memiliki struktur linguistik yang seragam, terutama untuk teks tidak formal, bahasa gaul, singkatan, atau typo (typhographical errors).

Contoh: Mengubah kata "bgt" menjadi "banget", "udh" menjadi "sudah", atau menstandarisasi penulisan angka dan simbol mata uang.

### Code

In [29]:
SLANG = {
    "apk": "aplikasi",
    "app": "aplikasi",
    "apps": "aplikasi",
    "eror": "error",
    "err": "error",
    "bug": "gangguan sistem",
    "lag": "lambat",
    "lemot": "lambat",
    "dwnld": "unduh",
    "download": "unduh",
    "updet": "perbarui",
    "update": "perbarui",
    "rekomended": "direkomendasikan",
    "recomended": "direkomendasikan",
    "recommended": "direkomendasikan",
    "worthit": "sepadan",
    "worth it": "sepadan",
    "fastrespon": "respons cepat",
    "utbk": "ujian tulis berbasis komputer",
    "snbt": "seleksi nasional berbasis tes",
    "snbp": "seleksi nasional berbasis prestasi",
    "tryout": "uji coba",
    "to": "uji coba",
    "mapel": "mata pelajaran",
    "mtk": "matematika",
    "mats": "matematika",
    "bing": "bahasa inggris",
    "bindo": "bahasa indonesia",
    "rg": "ruangguru",
    "pifi": "pahamify",
    "yg": "yang",
    "dg": "dengan",
    "dgn": "dengan",
    "utk": "untuk",
    "krn": "karena",
    "karna": "karena",
    "krna": "karena",
    "tdk": "tidak",
    "gak": "tidak",
    "ga": "tidak",
    "nggak": "tidak",
    "gk": "tidak",
    "enggak": "tidak",
    "engga": "tidak",
    "gaada": "tidak ada",
    "gakada": "tidak ada",
    "bkn": "bukan",
    "sdh": "sudah",
    "udh": "sudah",
    "udah": "sudah",
    "blm": "belum",
    "jg": "juga",
    "jga": "juga",
    "sm": "sama",
    "sma": "sama",
    "klo": "kalau",
    "kalo": "kalau",
    "klu": "kalau",
    "trus": "terus",
    "tp": "tapi",
    "tpi": "tapi",
    "aja": "saja",
    "bgt": "banget",
    "bgtt": "banget",
    "emg": "memang",
    "emang": "memang",
    "org": "orang",
    "dr": "dari",
    "dlm": "dalam",
    "pd": "pada",
    "sbg": "sebagai",
    "spt": "seperti",
    "stlah": "setelah",
    "gw": "saya",
    "gue": "saya",
    "gua": "saya",
    "lu": "kamu",
    "loe": "kamu",
    "sy": "saya",
    "sya": "saya",
    "ak": "aku",
    "bkn": "bukan",
    "dlu": "dulu",
    "dluu": "dulu",
    "makasih": "terima kasih",
    "makasii": "terima kasih",
    "mksih": "terima kasih",
    "trims": "terima kasih",
    "thanks": "terima kasih",
    "thx": "terima kasih",
    "tanks": "terima kasih",
    "tengkyu": "terima kasih",
    "bgs": "bagus",
    "bintang": "bintang",
    "btng": "bintang",
    "bintg": "bintang",
    "kesimpen": "tersimpan",
    "simpen": "simpan",
    "sampe": "sampai",
    "smpe": "sampai",
    "ampe": "sampai",
    "dapet": "dapat",
    "dpt": "dapat",
    "nonton": "menonton",
    "nyesel": "menyesal",
    "moga": "semoga",
    "moga2": "semoga",
    "bikin": "membuat",
    "kasi": "beri",
    "kasih": "beri",
    "gampang": "mudah",
    "mantul": "mantap betul",
    "mantap": "mantap",
    "mantab": "mantap",
    "asik": "asyik",
    "pake": "pakai",
    "pke": "pakai",
    "ngerti": "mengerti",
    "keliatan": "kelihatan",
    "ancur": "hancur",
    "liat": "lihat",
    "boong": "bohong",

}

In [30]:
def text_normalization(df, text_col, output_col="text_normalized", slang=SLANG):
    def norm(text):
        if not text: return ""
        text = unicodedata.normalize("NFKC", text).lower()
        text = re.sub(r"[“”„‟]", '"', text)
        text = re.sub(r"[‘’‚‛]", "'", text)
        text = re.sub(r"[—–]", " - ", text)
        text = re.sub(r"\b\w*(\w)\1{2,}\w*\b", _collapse, text)       # mantaaap -> mantap (angka Romawi dikecualikan)
        text = re.sub(r"\brp\s?(\d)", r"rp \1", text)                # rp76 -> rp 76
        text = re.sub(r"\b([a-z]+)2\b", r"\1-\1", text)             # tiba2 -> tiba-tiba
        text = re.sub(r"\b[a-z0-9]+\b", lambda m: slang.get(m.group(0), m.group(0)), text)
        return re.sub(r"\s+", " ", text).strip()
    return _apply_str(df, text_col, output_col, norm)

In [31]:
df_normalized = text_normalization(
    df_noise, text_col="text_clean"
)

In [32]:
df_normalized

shape: (200, 3)
┌────────────────────────────────┬────────────────────────────────┬────────────────────────────────┐
│ text                           ┆ text_clean                     ┆ text_normalized                │
│ ---                            ┆ ---                            ┆ ---                            │
│ str                            ┆ str                            ┆ str                            │
╞════════════════════════════════╪════════════════════════════════╪════════════════════════════════╡
│ Aplikasi cerdas ,cepat dan     ┆ Aplikasi cerdas ,cepat dan     ┆ aplikasi cerdas ,cepat dan     │
│ sim…                           ┆ sim…                           ┆ sim…                           │
│ aplikasi ruang guru sangat     ┆ aplikasi ruang guru sangat     ┆ aplikasi ruang guru sangat     │
│ mem…                           ┆ mem…                           ┆ mem…                           │
│ aplikasi nya jelek tapi        ┆ aplikasi nya jelek tapi        ┆ aplikasi nya jelek tapi bong   │
│ booong…                        ┆ booong…                        ┆ h…                             │
│ sebenarnya baru juga download  ┆ sebenarnya baru juga download  ┆ sebenarnya baru juga unduh     │
│ …                              ┆ …                              ┆ tap…                           │
│ baguss sih buat belajar,       ┆ baguss sih buat belajar,       ┆ baguss sih buat belajar,       │
│ mudah…                         ┆ mudah…                         ┆ mudah…                         │
│ …                              ┆ …                              ┆ …                              │
│ bagus aplikasinya, banyak      ┆ bagus aplikasinya, banyak      ┆ bagus aplikasinya, banyak      │
│ lati…                          ┆ lati…                          ┆ lati…                          │
│ hallo saya Agung Setiawan      ┆ hallo saya Agung Setiawan      ┆ hallo saya agung setiawan      │
│ dari…                          ┆ dari…                          ┆ dari…                          │
│ Bikin belajar bahasa inggris   ┆ Bikin belajar bahasa inggris   ┆ membuat belajar bahasa         │
│ m…                             ┆ m…                             ┆ inggris…                       │
│ Mohon dipermudahkan untuk      ┆ Mohon dipermudahkan untuk      ┆ mohon dipermudahkan untuk      │
│ masu…                          ┆ masu…                          ┆ masu…                          │
│ Thank you for the test...      ┆ Thank you for the test...      ┆ thank you for the test...      │
│ Pela…                          ┆ Pela…                          ┆ pela…                          │
└────────────────────────────────┴────────────────────────────────┴────────────────────────────────┘

## Tokenisasi

Memecah kalimat atau paragraf yang panjang menjadi unit-unit kecil yang disebut token (biasanya berupa kata atau frasa), hasilnya berupa list, bukan string..

Contoh: Kalimat "Saya sedang belajar NLP." dipecah menjadi: ["Saya", "sedang", "belajar", "NLP"].

### Code

In [33]:
# def tokenization(df, text_col, output_col="tokens"):
#     """
#     Memecah teks menjadi token kata.
#     Output setiap baris berupa list.
#     """
#     result = df.clone()

#     def tokenize_text(text):
#         if text is None:
#             return ""
#         # if pl.isna(text):
#         #     return []

#         text = str(text)

#         # Ambil rangkaian karakter alfanumerik.
#         # Kata dengan apostrof atau tanda hubung dipisah.
#         return re.findall(r"\b\w+\b", text, flags=re.UNICODE)

#     return df.with_columns(
#         df[text_col].map_elements(tokenize_text).alias(output_col)
#     )
#     # result[output_col] = result[text_col].apply(tokenize_text)
#     # return result

In [34]:
TOKEN_RE = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")
def tokenization(df, text_col, output_col="tokens"):
    return df.with_columns(
        pl.col(text_col).map_elements(lambda t: TOKEN_RE.findall(t or ""),
                                      return_dtype=pl.List(pl.Utf8)).alias(output_col))

In [35]:
df_tokens = tokenization(
    df_normalized, text_col="text_normalized"
)

In [36]:
df_tokens

shape: (200, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ text                   ┆ text_clean             ┆ text_normalized        ┆ tokens                │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ str                    ┆ str                    ┆ str                    ┆ list[str]             │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ Aplikasi cerdas ,cepat ┆ Aplikasi cerdas ,cepat ┆ aplikasi cerdas ,cepat ┆ ["aplikasi",          │
│ dan sim…               ┆ dan sim…               ┆ dan sim…               ┆ "cerdas", … "simp…    │
│ aplikasi ruang guru    ┆ aplikasi ruang guru    ┆ aplikasi ruang guru    ┆ ["aplikasi", "ruang", │
│ sangat mem…            ┆ sangat mem…            ┆ sangat mem…            ┆ … "memba…             │
│ aplikasi nya jelek     ┆ aplikasi nya jelek     ┆ aplikasi nya jelek     ┆ ["aplikasi", "nya", … │
│ tapi booong…           ┆ tapi booong…           ┆ tapi bong h…           ┆ "guru"]               │
│ sebenarnya baru juga   ┆ sebenarnya baru juga   ┆ sebenarnya baru juga   ┆ ["sebenarnya",        │
│ download …             ┆ download …             ┆ unduh tap…             ┆ "baru", … "ya"]       │
│ baguss sih buat        ┆ baguss sih buat        ┆ baguss sih buat        ┆ ["baguss", "sih", …   │
│ belajar, mudah…        ┆ belajar, mudah…        ┆ belajar, mudah…        ┆ "nya"]                │
│ …                      ┆ …                      ┆ …                      ┆ …                     │
│ bagus aplikasinya,     ┆ bagus aplikasinya,     ┆ bagus aplikasinya,     ┆ ["bagus",             │
│ banyak lati…           ┆ banyak lati…           ┆ banyak lati…           ┆ "aplikasinya", … "so… │
│ hallo saya Agung       ┆ hallo saya Agung       ┆ hallo saya agung       ┆ ["hallo", "saya", …   │
│ Setiawan dari…         ┆ Setiawan dari…         ┆ setiawan dari…         ┆ "bangsa"]             │
│ Bikin belajar bahasa   ┆ Bikin belajar bahasa   ┆ membuat belajar bahasa ┆ ["membuat",           │
│ inggris m…             ┆ inggris m…             ┆ inggris…               ┆ "belajar", … "asyi…   │
│ Mohon dipermudahkan    ┆ Mohon dipermudahkan    ┆ mohon dipermudahkan    ┆ ["mohon",             │
│ untuk masu…            ┆ untuk masu…            ┆ untuk masu…            ┆ "dipermudahkan", … "… │
│ Thank you for the      ┆ Thank you for the      ┆ thank you for the      ┆ ["thank", "you", …    │
│ test... Pela…          ┆ test... Pela…          ┆ test... pela…          ┆ "biasa"]              │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

## Stopwords Removal

Menghapus kata-kata umum yang sering muncul dalam suatu bahasa namun memiliki sedikit atau bahkan tidak memiliki makna analitik yang kuat.

Contoh: dan, yang, di, dari, ke, untuk

### Code

In [37]:
# Stopword bahasa Indonesia
stop_words = set(stopwords.words("indonesian"))

# Tambahan stopword opsional
custom_stopwords = {
    "yg", "dg", "dgn", "nya", "sih", "dong",
    "nih", "deh", "aja", "udah", "gak", "nggak"
}

stop_words.update(custom_stopwords)

In [38]:
print(stop_words)

{'antara', 'masa', 'tambah', 'bulan', 'menanti', 'berturut-turut', 'bung', 'lanjutnya', 'misalkan', 'dilalui', 'yakin', 'terjadinya', 'menanya', 'diberikannya', 'diperbuat', 'sepihak', 'jadinya', 'tertuju', 'menanyai', 'sedang', 'bagaimana', 'menggunakan', 'berikut', 'berakhirnya', 'artinya', 'bawah', 'dimisalkan', 'menghendaki', 'merekalah', 'saat', 'baru', 'benarkah', 'diperlihatkan', 'gak', 'sekalipun', 'bermacam-macam', 'jauh', 'sekadar', 'penting', 'itulah', 'sebanyak', 'melihatnya', 'sepantasnyalah', 'diketahui', 'teringat-ingat', 'sekitar', 'keadaan', 'selain', 'mengingat', 'agar', 'menunjuknya', 'nih', 'memperbuat', 'dini', 'dijelaskan', 'walaupun', 'panjang', 'menjelaskan', 'ikut', 'sendiri', 'umumnya', 'bersama', 'selanjutnya', 'siap', 'beberapa', 'menambahkan', 'selama-lamanya', 'dari', 'semuanya', 'tadinya', 'bertanya-tanya', 'punya', 'disinilah', 'seterusnya', 'terasa', 'ditanyai', 'jumlahnya', 'apabila', 'tadi', 'terkira', 'kok', 'bagi', 'pertanyaan', 'bagai', 'dikatakan', 'ditanyakan', 'tambahnya', 'dipunyai', 'menyeluruh', 'caranya', 'setibanya', 'akhiri', 'tidak', 'sejumlah', 'tersampaikan', 'bisakah', 'memang', 'sekaligus', 'besar', 'siapa', 'terutama', 'sebesar', 'meyakinkan', 'bahwasanya', 'sebagaimana', 'memerlukan', 'semula', 'kemungkinan', 'tegasnya', 'berakhir', 'saya', 'terakhir', 'sementara', 'begitukah', 'sejenak', 'padanya', 'sebagai', 'bagaimanapun', 'nanti', 'seperlunya', 'diperbuatnya', 'berlalu', 'beri', 'cuma', 'sehingga', 'mendapatkan', 'lebih', 'sekali', 'mendatangkan', 'luar', 'macam', 'nyatanya', 'rupanya', 'kamilah', 'bilakah', 'sedemikian', 'tidaklah', 'kelihatannya', 'akankah', 'nah', 'sana', 'akulah', 'dituturkannya', 'mungkin', 'sebelum', 'mempertanyakan', 'andalah', 'menyiapkan', 'sama', 'lain', 'meski', 'mendatangi', 'naik', 'siapapun', 'kitalah', 'pula', 'pasti', 'kan', 'dong', 'mengibaratkan', 'kini', 'lewat', 'sesaat', 'sebaliknya', 'inilah', 'telah', 'sebutlah', 'akhir', 'terdapat', 'sesuatu', 'sela', 'paling', 'berlangsung', 'hal', 'aku', 'awal', 'sedikit', 'sendirian', 'seseorang', 'sebisanya', 'yaitu', 'sama-sama', 'kepadanya', 'waduh', 'tertentu', 'ditunjuk', 'tandasnya', 'belakang', 'usah', 'meyakini', 'ditunjuki', 'sebaiknya', 'diri', 'mulailah', 'balik', 'setempat', 'kapan', 'lagi', 'beginilah', 'dibuat', 'ke', 'tersebutlah', 'demikian', 'mulai', 'diperlukannya', 'terdahulu', 'sebagian', 'sempat', 'ungkapnya', 'begitu', 'menyebutkan', 'belum', 'diperkirakan', 'saatnya', 'berapalah', 'sebuah', 'harusnya', 'tandas', 'dimaksudkan', 'menegaskan', 'mengenai', 'seenaknya', 'serupa', 'jelaskan', 'kamulah', 'mempersiapkan', 'semasa', 'sekurang-kurangnya', 'berikan', 'biasanya', 'maka', 'menyatakan', 'setinggi', 'dimulai', 'dikarenakan', 'sudahlah', 'sebabnya', 'keluar', 'menunjukkan', 'manakala', 'mengucapkannya', 'dijelaskannya', 'begitupun', 'dalam', 'mau', 'mempergunakan', 'jawaban', 'di', 'menantikan', 'mengatakan', 'agak', 'manalagi', 'seharusnya', 'menunjuk', 'berikutnya', 'bagian', 'tanpa', 'tak', 'masihkah', 'diantara', 'sebegini', 'berupa', 'diantaranya', 'sekarang', 'baik', 'digunakan', 'dimintai', 'memastikan', 'waktu', 'tentang', 'tepat', 'lalu', 'berawal', 'seingat', 'wah', 'kapankah', 'sepertinya', 'sebagainya', 'semaunya', 'pihak', 'saling', 'semasih', 'inginkan', 'sesama', 'apakah', 'entah', 'lagian', 'membuat', 'soal', 'tampak', 'rasa', 'seketika', 'bahkan', 'lainnya', 'setiap', 'deh', 'sepantasnya', 'boleh', 'pertama-tama', 'dgn', 'ditanya', 'banyak', 'sebelumnya', 'semata', 'berkenaan', 'diibaratkannya', 'masing-masing', 'awalnya', 'dimulainya', 'dipersoalkan', 'olehnya', 'daripada', 'disebutkannya', 'seringnya', 'tegas', 'jadi', 'masih', 'disampaikan', 'demi', 'sampaikan', 'dimulailah', 'diinginkan', 'adanya', 'belumlah', 'menunjuki', 'dipertanyakan', 'tengah', 'dahulu', 'sebenarnya', 'namun', 'hampir', 'bahwa', 'memihak', 'sekurangnya', 'bolehlah', 'percuma', 'terbanyak', 'teringat', 'memungkinkan', 'depan', 'diingat', 'pentingnya', 'terlalu', 'maupun', 'sebetulnya', 'untuk', 'karenanya', 'seolah', 'ditambahkan', 'segala', 'melainkan', 'dipergunakan', 'sini', 'sebab', 'ditunjuknya', 'sekiranya', 'diungkapkan', 'kita', 'berada', 'seolah-olah', 'bukannya', 'sejak', 'terjadi', 'ditegaskan', 'ditunjukkannya', 'sedangkan', 'seluruhnya', 'lima', 'hendaknya', 'memisalkan', 'sesudah', 'tanyakan', 'apa', 'yakni', 'sesampai', 'tetap', 'ingin', 'diucapkan', 'sewaktu', 'apalagi', 'masalah', 'begini', 'siapakah', 'inginkah', 'semisal', 'tanyanya', 'diminta', 'dituturkan', 'kemungkinannya', 'melalui', 'dibuatnya', 'selaku', 'terlebih', 'mendatang', 'segalanya', 'bakal', 'enggaknya', 'ungkap', 'melihat', 'setidaknya', 'sudah', 'kiranya', 'setengah', 'merasa', 'sekali-kali', 'terhadap', 'biasa', 'segera', 'kasus', 'tiba', 'inikah', 'ujarnya', 'udah', 'tahun', 'ia', 'berkeinginan', 'jika', 'jelasnya', 'tahu', 'diketahuinya', 'jelas', 'tiga', 'sebegitu', 'ibaratkan', 'jumlah', 'suatu', 'diingatkan', 'ucapnya', 'dimaksud', 'pak', 'sekalian', 'ini', 'setidak-tidaknya', 'kelihatan', 'enggak', 'sepanjang', 'bisa', 'didapat', 'perlu', 'sih', 'pukul', 'amat', 'malah', 'tuturnya', 'berapapun', 'ucap', 'disebutkan', 'amatlah', 'demikianlah', 'pertanyakan', 'mempersoalkan', 'seorang', 'selamanya', 'justru', 'pun', 'kepada', 'mengakhiri', 'asal', 'lanjut', 'pernah', 'betulkah', 'ataupun', 'berkali-kali', 'memintakan', 'kenapa', 'khususnya', 'mampukah', 'menyampaikan', 'yang', 'ialah', 'entahlah', 'didatangkan', 'tempat', 'buat', 'keinginan', 'berjumlah', 'hari', 'aja', 'mirip', 'kurang', 'walau', 'bekerja', 'apaan', 'dipastikan', 'jangankan', 'dg', 'antar', 'lama', 'sudahkah', 'usai', 'kalau', 'keduanya', 'tinggi', 'karena', 'sesegera', 'pihaknya', 'dekat', 'terhadapnya', 'diibaratkan', 'selalu', 'berarti', 'pada', 'berlainan', 'mengira', 'agaknya', 'sambil', 'oleh', 'masing', 'cukuplah', 'ingat-ingat', 'beginian', 'mulanya', 'menyangkut', 'menuju', 'yg', 'sesuatunya', 'dirinya', 'tersebut', 'atas', 'tapi', 'bersama-sama', 'bermula', 'soalnya', 'persoalan', 'berkehendak', 'disini', 'ditunjukkan', 'lamanya', 'tiap', 'menandaskan', 'hingga', 'kecil', 'juga', 'perlunya', 'terus', 'misalnya', 'adalah', 'dilakukan', 'cara', 'menurut', 'anda', 'dua', 'berakhirlah', 'bertanya', 'berlebihan', 'rasanya', 'sampai', 'semampunya', 'se', 'semakin', 'kesampaian', 'apatah', 'memperlihatkan', 'satu', 'sebutnya', 'tiba-tiba', 'sangat', 'berujar', 'rata', 'semua', 'wong', 'setiba', 'selama', 'itukah', 'katakan', 'tentunya', 'jawabnya', 'terjadilah', 'katakanlah', 'semampu', 'perlukah', 'makin', 'adapun', 'dapat', 'kalaulah', 'dijawab', 'kebetulan', 'meskipun', 'diakhiri', 'sebut', 'makanya', 'sekecil', 'diperlukan', 'hanyalah', 'jelaslah', 'bagaikan', 'tetapi', 'keterlaluan', 'kelamaan', 'ada', 'jangan', 'padahal', 'begitulah', 'seperti', 'tunjuk', 'kinilah', 'bermaksud', 'tidakkah', 'bagaimanakah', 'dengan', 'berapa', 'memberikan', 'menjadi', 'malahan', 'ditandaskan', 'merupakan', 'berkata', 'semata-mata', 'toh', 'mengingatkan', 'kami', 'secara', 'hendak', 'termasuk', 'jawab', 'betul', 'meminta', 'haruslah', 'kelima', 'keseluruhannya', 'sedikitnya', 'berbagai', 'cukupkah', 'dimaksudnya', 'nya', 'nantinya', 'dia', 'mengapa', 'menanyakan', 'secukupnya', 'saja', 'umum', 'para', 'seluruh', 'jikalau', 'semacam', 'bakalan', 'keseluruhan', 'janganlah', 'bila', 'cukup', 'kalian', 'dikerjakan', 'dikira', 'per', 'turut', 'mungkinkah', 'menginginkan', 'berdatangan', 'beginikah', 'tentulah', 'mampu', 'kalaupun', 'kedua', 'diberikan', 'kata', 'sendirinya', 'pantas', 'sekitarnya', 'diucapkannya', 'benarlah', 'gunakan', 'belakangan', 'bukanlah', 'mendapat', 'serta', 'menaiki', 'berturut', 'mula', 'sekadarnya', 'bukan', 'minta', 'disebut', 'tutur', 'memperkirakan', 'menanti-nanti', 'bolehkah', 'ibaratnya', 'kira', 'kira-kira', 'bertutur', 'mereka', 'benar', 'guna', 'kembali', 'tanya', 'setelah', 'masalahnya', 'asalkan', 'ibu', 'dilihat', 'lah', 'bersiap', 'harus', 'ingat', 'sampai-sampai', 'hanya', 'sajalah', 'terlihat', 'kala', 'kamu', 'sebaik', 'pertama', 'kapanpun', 'dulu', 'melakukan', 'mengetahui', 'hendaklah', 'mengerjakan', 'semisalnya', 'sering', 'sesekali', 'seusai', 'bersiap-siap', 'mana', 'dimungkinkan', 'mengatakannya', 'tampaknya', 'katanya', 'mengucapkan', 'mengibaratkannya', 'misal', 'ataukah', 'menjawab', 'itu', 'ketika', 'menuturkan', 'mengungkapkan', 'kemudian', 'datang', 'sinilah', 'terdiri', 'supaya', 'memulai', 'empat', 'sesudahnya', 'nyaris', 'dialah', 'mempunyai', 'dan', 'ujar', 'wahai', 'memberi', 'ibarat', 'sayalah', 'seberapa', 'pastilah', 'akan', 'ditujukan', 'berapakah', 'diakhirinya', 'dimaksudkannya', 'sangatlah', 'atau', 'diberi', 'jadilah', 'akhirnya', 'tentu', 'bermacam', 'waktunya', 'ternyata', 'sejauh', 'bapak', 'sebaik-baiknya', 'dikatakannya', 'bukankah', 'nggak', 'antaranya'}

In [39]:
def build_stopwords(keep_negation=True):
    sw = set(stopwords.words("indonesian"))
    sw |= {"sih", "dong", "nih", "deh", "kok", "lah", "kan", "nya", "tuh", "nah", "yah", "ya"}
    if keep_negation:
        sw -= {"tidak", "bukan", "tak", "belum", "jangan", "tanpa"}
    return sw

def stopword_removal(df, text_col, output_col="tokens_no_stopwords", stop_words=None):
    stop_words = stop_words or build_stopwords()
    return _apply_list(df, text_col, output_col,
                       lambda toks: [t for t in toks if t not in stop_words and len(t) > 1])

In [40]:
df_no_stopwords = stopword_removal(
    df_tokens, text_col="tokens"
)

In [41]:
df_no_stopwords

shape: (200, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ text              ┆ text_clean        ┆ text_normalized   ┆ tokens            ┆ tokens_no_stopwo │
│ ---               ┆ ---               ┆ ---               ┆ ---               ┆ rds              │
│ str               ┆ str               ┆ str               ┆ list[str]         ┆ ---              │
│                   ┆                   ┆                   ┆                   ┆ list[str]        │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ Aplikasi cerdas   ┆ Aplikasi cerdas   ┆ aplikasi cerdas   ┆ ["aplikasi",      ┆ ["aplikasi",     │
│ ,cepat dan sim…   ┆ ,cepat dan sim…   ┆ ,cepat dan sim…   ┆ "cerdas", …       ┆ "cerdas", …      │
│                   ┆                   ┆                   ┆ "simp…            ┆ "simp…           │
│ aplikasi ruang    ┆ aplikasi ruang    ┆ aplikasi ruang    ┆ ["aplikasi",      ┆ ["aplikasi",     │
│ guru sangat mem…  ┆ guru sangat mem…  ┆ guru sangat mem…  ┆ "ruang", …        ┆ "ruang", …       │
│                   ┆                   ┆                   ┆ "memba…           ┆ "memba…          │
│ aplikasi nya      ┆ aplikasi nya      ┆ aplikasi nya      ┆ ["aplikasi",      ┆ ["aplikasi",     │
│ jelek tapi        ┆ jelek tapi        ┆ jelek tapi bong   ┆ "nya", … "guru"]  ┆ "jelek", …       │
│ booong…           ┆ booong…           ┆ h…                ┆                   ┆ "guru"…          │
│ sebenarnya baru   ┆ sebenarnya baru   ┆ sebenarnya baru   ┆ ["sebenarnya",    ┆ ["unduh", "pas", │
│ juga download …   ┆ juga download …   ┆ juga unduh tap…   ┆ "baru", … "ya"]   ┆ … "bintang"]     │
│ baguss sih buat   ┆ baguss sih buat   ┆ baguss sih buat   ┆ ["baguss", "sih", ┆ ["baguss",       │
│ belajar, mudah…   ┆ belajar, mudah…   ┆ belajar, mudah…   ┆ … "nya"]          ┆ "belajar", …     │
│                   ┆                   ┆                   ┆                   ┆ "kedep…          │
│ …                 ┆ …                 ┆ …                 ┆ …                 ┆ …                │
│ bagus             ┆ bagus             ┆ bagus             ┆ ["bagus",         ┆ ["bagus",        │
│ aplikasinya,      ┆ aplikasinya,      ┆ aplikasinya,      ┆ "aplikasinya", …  ┆ "aplikasinya",   │
│ banyak lati…      ┆ banyak lati…      ┆ banyak lati…      ┆ "so…              ┆ "lati…           │
│ hallo saya Agung  ┆ hallo saya Agung  ┆ hallo saya agung  ┆ ["hallo", "saya", ┆ ["hallo",        │
│ Setiawan dari…    ┆ Setiawan dari…    ┆ setiawan dari…    ┆ … "bangsa"]       ┆ "agung", …       │
│                   ┆                   ┆                   ┆                   ┆ "bangsa"]        │
│ Bikin belajar     ┆ Bikin belajar     ┆ membuat belajar   ┆ ["membuat",       ┆ ["belajar",      │
│ bahasa inggris m… ┆ bahasa inggris m… ┆ bahasa inggris…   ┆ "belajar", …      ┆ "bahasa", …      │
│                   ┆                   ┆                   ┆ "asyi…            ┆ "asyik…          │
│ Mohon             ┆ Mohon             ┆ mohon             ┆ ["mohon",         ┆ ["mohon",        │
│ dipermudahkan     ┆ dipermudahkan     ┆ dipermudahkan     ┆ "dipermudahkan",  ┆ "dipermudahkan", │
│ untuk masu…       ┆ untuk masu…       ┆ untuk masu…       ┆ … "…              ┆ … "…             │
│ Thank you for the ┆ Thank you for the ┆ thank you for the ┆ ["thank", "you",  ┆ ["thank", "you", │
│ test... Pela…     ┆ test... Pela…     ┆ test... pela…     ┆ … "biasa"]        ┆ … "pelajaran"…   │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

In [43]:
df_no_stopwords['tokens_no_stopwords'][6]

shape: (3,)
Series: '' [str]
[
	"bintang"
	"belom"
	"mendowload"
]

## Stemming

Proses memotong imbuhan (prefiks, sufiks, infiks) pada sebuah kata untuk dikembalikan ke bentuk dasarnya (stem), tanpa selalu memperhatikan kaidah kamus yang valid.

Contoh: Kata "memakan", "dimakan", dan "termakan" akan diubah menjadi akar kata dasar "makan".

### Code

In [44]:
# Inisialisasi stemmer bahasa Indonesia
factory = StemmerFactory()
stemmer = factory.create_stemmer()

In [45]:
import polars as pl

def to_list(v):
    """Mengubah pl.Series atau iterables lainnya menjadi list Python."""
    if v is None:
        return []
    if isinstance(v, pl.Series):
        return v.to_list()
    if isinstance(v, list):
        return v
    return list(v)

def stemming(df: pl.DataFrame, text_col: str, output_col: str = "tokens_stemmed"):
    """
    Melakukan stemming menggunakan Sastrawi dengan aman dari noise metadata.
    """
    def stem_text(value):
        # Konversi nilai baris (bisa string, list, atau pl.Series) menjadi list token yang bersih
        if value is None:
            tokens = []
        elif isinstance(value, pl.Series):
            tokens = value.to_list()
        elif isinstance(value, list):
            tokens = value
        else:
            # Jika berupa string teks biasa (belum berupa list token)
            tokens = str(value).split()

        # Lakukan stemming pada setiap token
        return [stemmer.stem(str(token)) for token in tokens if token is not None]

    return df.with_columns(
        df[text_col].map_elements(
            stem_text,
            return_dtype=pl.List(pl.Utf8)
        ).alias(output_col)
    )

In [46]:
df_stemmed = stemming(
    df_no_stopwords, text_col="tokens_no_stopwords"
)

In [47]:
df_stemmed

shape: (200, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ text           ┆ text_clean     ┆ text_normalize ┆ tokens        ┆ tokens_no_sto ┆ tokens_stemme │
│ ---            ┆ ---            ┆ d              ┆ ---           ┆ pwords        ┆ d             │
│ str            ┆ str            ┆ ---            ┆ list[str]     ┆ ---           ┆ ---           │
│                ┆                ┆ str            ┆               ┆ list[str]     ┆ list[str]     │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ Aplikasi       ┆ Aplikasi       ┆ aplikasi       ┆ ["aplikasi",  ┆ ["aplikasi",  ┆ ["aplikasi",  │
│ cerdas ,cepat  ┆ cerdas ,cepat  ┆ cerdas ,cepat  ┆ "cerdas", …   ┆ "cerdas", …   ┆ "cerdas", …   │
│ dan sim…       ┆ dan sim…       ┆ dan sim…       ┆ "simp…        ┆ "simp…        ┆ "simp…        │
│ aplikasi ruang ┆ aplikasi ruang ┆ aplikasi ruang ┆ ["aplikasi",  ┆ ["aplikasi",  ┆ ["aplikasi",  │
│ guru sangat    ┆ guru sangat    ┆ guru sangat    ┆ "ruang", …    ┆ "ruang", …    ┆ "ruang", …    │
│ mem…           ┆ mem…           ┆ mem…           ┆ "memba…       ┆ "memba…       ┆ "bantu…       │
│ aplikasi nya   ┆ aplikasi nya   ┆ aplikasi nya   ┆ ["aplikasi",  ┆ ["aplikasi",  ┆ ["aplikasi",  │
│ jelek tapi     ┆ jelek tapi     ┆ jelek tapi     ┆ "nya", …      ┆ "jelek", …    ┆ "jelek", …    │
│ booong…        ┆ booong…        ┆ bong h…        ┆ "guru"]       ┆ "guru"…       ┆ "guru"…       │
│ sebenarnya     ┆ sebenarnya     ┆ sebenarnya     ┆ ["sebenarnya" ┆ ["unduh",     ┆ ["unduh",     │
│ baru juga      ┆ baru juga      ┆ baru juga      ┆ , "baru", …   ┆ "pas", …      ┆ "pas", …      │
│ download …     ┆ download …     ┆ unduh tap…     ┆ "ya"]         ┆ "bintang"]    ┆ "bintang"]    │
│ baguss sih     ┆ baguss sih     ┆ baguss sih     ┆ ["baguss",    ┆ ["baguss",    ┆ ["baguss",    │
│ buat belajar,  ┆ buat belajar,  ┆ buat belajar,  ┆ "sih", …      ┆ "belajar", …  ┆ "ajar", …     │
│ mudah…         ┆ mudah…         ┆ mudah…         ┆ "nya"]        ┆ "kedep…       ┆ "depan"]      │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ bagus          ┆ bagus          ┆ bagus          ┆ ["bagus", "ap ┆ ["bagus", "ap ┆ ["bagus",     │
│ aplikasinya,   ┆ aplikasinya,   ┆ aplikasinya,   ┆ likasinya", … ┆ likasinya",   ┆ "aplikasi",   │
│ banyak lati…   ┆ banyak lati…   ┆ banyak lati…   ┆ "so…          ┆ "lati…        ┆ "latih"]      │
│ hallo saya     ┆ hallo saya     ┆ hallo saya     ┆ ["hallo",     ┆ ["hallo",     ┆ ["hallo",     │
│ Agung Setiawan ┆ Agung Setiawan ┆ agung setiawan ┆ "saya", …     ┆ "agung", …    ┆ "agung", …    │
│ dari…          ┆ dari…          ┆ dari…          ┆ "bangsa"]     ┆ "bangsa"]     ┆ "bangsa"]     │
│ Bikin belajar  ┆ Bikin belajar  ┆ membuat        ┆ ["membuat",   ┆ ["belajar",   ┆ ["ajar",      │
│ bahasa inggris ┆ bahasa inggris ┆ belajar bahasa ┆ "belajar", …  ┆ "bahasa", …   ┆ "bahasa", …   │
│ m…             ┆ m…             ┆ inggris…       ┆ "asyi…        ┆ "asyik…       ┆ "asyik"]      │
│ Mohon          ┆ Mohon          ┆ mohon          ┆ ["mohon", "di ┆ ["mohon", "di ┆ ["mohon",     │
│ dipermudahkan  ┆ dipermudahkan  ┆ dipermudahkan  ┆ permudahkan", ┆ permudahkan", ┆ "mudah", …    │
│ untuk masu…    ┆ untuk masu…    ┆ untuk masu…    ┆ … "…          ┆ … "…          ┆ "kasih"]      │
│ Thank you for  ┆ Thank you for  ┆ thank you for  ┆ ["thank",     ┆ ["thank",     ┆ ["thank",     │
│ the test...    ┆ the test...    ┆ the test...    ┆ "you", …      ┆ "you", …      ┆ "you", …      │
│ Pela…          ┆ Pela…          ┆ pela…          ┆ "biasa"]      ┆ "pelajaran"…  ┆ "ajar"]       │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [ ]:
# STEM_EXCEPTIONS = {"belasan": "belas"}
# PROTECTED = {"wantimpres", "gibran", "prabowo", "rocky", "gerung", "pratikno", "dpr"}

In [ ]:
# _stemmer = StemmerFactory().create_stemmer()
# @lru_cache(maxsize=None)
# def _stem(tok):
#     if tok in PROTECTED or tok.isdigit() or "-" in tok: return tok
#     if tok in STEM_EXCEPTIONS: return STEM_EXCEPTIONS[tok]
#     return _stemmer.stem(tok)

# def stemming(df, text_col, output_col="tokens_stemmed"):
#     return _apply_list(df, text_col, output_col, lambda toks: [_stem(t) for t in toks])

In [48]:
df_stemmed['tokens_stemmed'][0]

shape: (4,)
Series: '' [str]
[
	"aplikasi"
	"cerdas"
	"cepat"
	"simple"
]

## Lemmatization

Proses mengubah kata berimbuhan menjadi bentuk dasarnya berdasarkan kamus dan tata bahasa yang valid (lemma), dengan memperhatikan konteks kalimat. Berbeda dengan stemming, proses ini idealnya menghasilkan bentuk lema yang valid secara linguistik.

Isi kamus lemma sebaiknya ditentukan dari kata berimbuhan yang benar-benar sering muncul dari data, bukan contoh umum. aturan untuk menentukan niai lema bisasnya menggunakan beberaoa ruls seperti:
1. Kalau imbuhan hanya mengubah bentuk gramatikal tanpa mengubah makna inti (dilantik → lantik), pakai kata dasar.

2. Kalau kata berimbuhan sudah punya makna sendiri yang berbeda dari kata dasarnya (pemerintah, kebijakan, anggaran, alasan), pertahankan bentuk aslinya sebagai lemma.

### Cek

### Code

In [50]:

LEMMA_DICTIONARY = {
    "membantu": "bantu",
    "membeli": "beli",
    "membuat": "buat",
    "memahami": "paham",
    "memperbaiki": "baik",
    "mempermudah": "mudah",
    "membalas": "balas",
    "membuka": "buka",
    "melihat": "lihat",
    "menonton": "tonton",
    "menjawab": "jawab",
    "menjelaskan": "jelas",
    "mengetahui": "tahu",
    "mengerti": "erti",
    "menginstal": "instal",
    "mengunduh": "unduh",
    "menggunakan": "guna",
    "mengisi": "isi",
    "menyampaikan": "sampai",
    "menyenangkan": "senang",
    "menambah": "tambah",
    "mendorong": "dorong",
    "meningkatkan": "tingkat",
    "diperbaiki": "baik",
    "dimengerti": "erti",
    "dipahami": "paham",
    "digunakan": "guna",
    "diharapkan": "harap",
    "diberikan": "beri",
    "dibantu": "bantu",
    "dibeli": "beli",
    "diunduh": "unduh",
    "berjalan": "jalan",
    "berfungsi": "fungsi",
    "berkarya": "karya",
    "berkembang": "kembang",
    "bermanfaat": "manfaat",
    "berlangganan": "langgan",
    "terbantu": "bantu",
    "terpakai": "pakai",
    "tersimpan": "simpan",
    "terjadi": "jadi",
    "aplikasinya": "aplikasi",
    "videonya": "video",
    "soalnya": "soal",
    "materinya": "materi",
    "sekolahnya": "sekolah",
    "fiturnya": "fitur",
    "kakaknya": "kakak",
    "belajarmu": "belajar",
    "dukunganmu": "dukung",
    "tambahin": "tambah",
    "kasihlah": "kasih",
    "berikan": "beri",
    "masukkan": "masuk",
    "pahami": "paham",
    "perkembangan": "kembang",
    "pembelajaran": "ajar",
    "pelajaran": "ajar",
    "pengajaran": "ajar",
    "ketidaknyamanan": "nyaman",
    "kenyamanan": "nyaman",
    "kepercayaan": "percaya",
    "penyemangat": "semangat",
    "bimbingan": "bimbing",
    "jawaban": "jawab",
    "penjelasan": "jelas",
    "sebulannya": "bulan",
}

In [51]:

def lemmatization(
    df: pl.DataFrame,
    text_col: str,
    output_col: str = "tokens_lemmatized",
    lemma_dict: dict = None
):
    """
    Lemmatization berbasis kamus.
    Kata yang tidak ada dalam kamus dipertahankan.
    """
    if lemma_dict is None:
        lemma_dict = lemma_dictionary

    def lemmatize_text(value):
        if value is None:
            return []
        # kolom list di Polars masuk sebagai pl.Series -> ubah ke list Python
        if isinstance(value, pl.Series):
            tokens = value.to_list()
        elif isinstance(value, list):
            tokens = value
        else:
            tokens = str(value).split()

        return [lemma_dict.get(str(t).lower(), str(t).lower()) for t in tokens]

    return df.with_columns(
        pl.col(text_col).map_elements(
            lemmatize_text,
            return_dtype=pl.List(pl.Utf8)
        ).alias(output_col)
    )

In [52]:
df_lemmatized = lemmatization(
    df_no_stopwords, text_col="tokens_no_stopwords"
)

In [53]:
df_lemmatized

shape: (200, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ text           ┆ text_clean     ┆ text_normalize ┆ tokens        ┆ tokens_no_sto ┆ tokens_lemmat │
│ ---            ┆ ---            ┆ d              ┆ ---           ┆ pwords        ┆ ized          │
│ str            ┆ str            ┆ ---            ┆ list[str]     ┆ ---           ┆ ---           │
│                ┆                ┆ str            ┆               ┆ list[str]     ┆ list[str]     │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ Aplikasi       ┆ Aplikasi       ┆ aplikasi       ┆ ["aplikasi",  ┆ ["aplikasi",  ┆ ["aplikasi",  │
│ cerdas ,cepat  ┆ cerdas ,cepat  ┆ cerdas ,cepat  ┆ "cerdas", …   ┆ "cerdas", …   ┆ "cerdas", …   │
│ dan sim…       ┆ dan sim…       ┆ dan sim…       ┆ "simp…        ┆ "simp…        ┆ "simp…        │
│ aplikasi ruang ┆ aplikasi ruang ┆ aplikasi ruang ┆ ["aplikasi",  ┆ ["aplikasi",  ┆ ["aplikasi",  │
│ guru sangat    ┆ guru sangat    ┆ guru sangat    ┆ "ruang", …    ┆ "ruang", …    ┆ "ruang", …    │
│ mem…           ┆ mem…           ┆ mem…           ┆ "memba…       ┆ "memba…       ┆ "memba…       │
│ aplikasi nya   ┆ aplikasi nya   ┆ aplikasi nya   ┆ ["aplikasi",  ┆ ["aplikasi",  ┆ ["aplikasi",  │
│ jelek tapi     ┆ jelek tapi     ┆ jelek tapi     ┆ "nya", …      ┆ "jelek", …    ┆ "jelek", …    │
│ booong…        ┆ booong…        ┆ bong h…        ┆ "guru"]       ┆ "guru"…       ┆ "guru"…       │
│ sebenarnya     ┆ sebenarnya     ┆ sebenarnya     ┆ ["sebenarnya" ┆ ["unduh",     ┆ ["unduh",     │
│ baru juga      ┆ baru juga      ┆ baru juga      ┆ , "baru", …   ┆ "pas", …      ┆ "pas", …      │
│ download …     ┆ download …     ┆ unduh tap…     ┆ "ya"]         ┆ "bintang"]    ┆ "bintang"]    │
│ baguss sih     ┆ baguss sih     ┆ baguss sih     ┆ ["baguss",    ┆ ["baguss",    ┆ ["baguss",    │
│ buat belajar,  ┆ buat belajar,  ┆ buat belajar,  ┆ "sih", …      ┆ "belajar", …  ┆ "belajar", …  │
│ mudah…         ┆ mudah…         ┆ mudah…         ┆ "nya"]        ┆ "kedep…       ┆ "kedep…       │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ bagus          ┆ bagus          ┆ bagus          ┆ ["bagus", "ap ┆ ["bagus", "ap ┆ ["bagus", "ap │
│ aplikasinya,   ┆ aplikasinya,   ┆ aplikasinya,   ┆ likasinya", … ┆ likasinya",   ┆ likasinya",   │
│ banyak lati…   ┆ banyak lati…   ┆ banyak lati…   ┆ "so…          ┆ "lati…        ┆ "lati…        │
│ hallo saya     ┆ hallo saya     ┆ hallo saya     ┆ ["hallo",     ┆ ["hallo",     ┆ ["hallo",     │
│ Agung Setiawan ┆ Agung Setiawan ┆ agung setiawan ┆ "saya", …     ┆ "agung", …    ┆ "agung", …    │
│ dari…          ┆ dari…          ┆ dari…          ┆ "bangsa"]     ┆ "bangsa"]     ┆ "bangsa"]     │
│ Bikin belajar  ┆ Bikin belajar  ┆ membuat        ┆ ["membuat",   ┆ ["belajar",   ┆ ["belajar",   │
│ bahasa inggris ┆ bahasa inggris ┆ belajar bahasa ┆ "belajar", …  ┆ "bahasa", …   ┆ "bahasa", …   │
│ m…             ┆ m…             ┆ inggris…       ┆ "asyi…        ┆ "asyik…       ┆ "asyik…       │
│ Mohon          ┆ Mohon          ┆ mohon          ┆ ["mohon", "di ┆ ["mohon", "di ┆ ["mohon", "di │
│ dipermudahkan  ┆ dipermudahkan  ┆ dipermudahkan  ┆ permudahkan", ┆ permudahkan", ┆ permudahkan", │
│ untuk masu…    ┆ untuk masu…    ┆ untuk masu…    ┆ … "…          ┆ … "…          ┆ … "…          │
│ Thank you for  ┆ Thank you for  ┆ thank you for  ┆ ["thank",     ┆ ["thank",     ┆ ["thank",     │
│ the test...    ┆ the test...    ┆ the test...    ┆ "you", …      ┆ "you", …      ┆ "you", …      │
│ Pela…          ┆ Pela…          ┆ pela…          ┆ "biasa"]      ┆ "pelajaran"…  ┆ "pelajaran"…  │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

## Hasil

In [54]:
columns_to_view = [
    "text",
    "text_clean",
    "text_normalized",
    "tokens",
    "tokens_no_stopwords",
    "tokens_stemmed",
    "tokens_lemmatized"
]

df_comparison = (
    df_lemmatized
    .with_columns(df_stemmed["tokens_stemmed"])
    .select(columns_to_view)
)

df_comparison.head()

shape: (5, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ text         ┆ text_clean  ┆ text_normal ┆ tokens      ┆ tokens_no_s ┆ tokens_stem ┆ tokens_lemm │
│ ---          ┆ ---         ┆ ized        ┆ ---         ┆ topwords    ┆ med         ┆ atized      │
│ str          ┆ str         ┆ ---         ┆ list[str]   ┆ ---         ┆ ---         ┆ ---         │
│              ┆             ┆ str         ┆             ┆ list[str]   ┆ list[str]   ┆ list[str]   │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ Aplikasi     ┆ Aplikasi    ┆ aplikasi    ┆ ["aplikasi" ┆ ["aplikasi" ┆ ["aplikasi" ┆ ["aplikasi" │
│ cerdas       ┆ cerdas      ┆ cerdas      ┆ , "cerdas", ┆ , "cerdas", ┆ , "cerdas", ┆ , "cerdas", │
│ ,cepat dan   ┆ ,cepat dan  ┆ ,cepat dan  ┆ … "simp…    ┆ … "simp…    ┆ … "simp…    ┆ … "simp…    │
│ sim…         ┆ sim…        ┆ sim…        ┆             ┆             ┆             ┆             │
│ aplikasi     ┆ aplikasi    ┆ aplikasi    ┆ ["aplikasi" ┆ ["aplikasi" ┆ ["aplikasi" ┆ ["aplikasi" │
│ ruang guru   ┆ ruang guru  ┆ ruang guru  ┆ , "ruang",  ┆ , "ruang",  ┆ , "ruang",  ┆ , "ruang",  │
│ sangat mem…  ┆ sangat mem… ┆ sangat mem… ┆ … "memba…   ┆ … "memba…   ┆ … "bantu…   ┆ … "memba…   │
│ aplikasi nya ┆ aplikasi    ┆ aplikasi    ┆ ["aplikasi" ┆ ["aplikasi" ┆ ["aplikasi" ┆ ["aplikasi" │
│ jelek tapi   ┆ nya jelek   ┆ nya jelek   ┆ , "nya", …  ┆ , "jelek",  ┆ , "jelek",  ┆ , "jelek",  │
│ booong…      ┆ tapi        ┆ tapi bong   ┆ "guru"]     ┆ … "guru"…   ┆ … "guru"…   ┆ … "guru"…   │
│              ┆ booong…     ┆ h…          ┆             ┆             ┆             ┆             │
│ sebenarnya   ┆ sebenarnya  ┆ sebenarnya  ┆ ["sebenarny ┆ ["unduh",   ┆ ["unduh",   ┆ ["unduh",   │
│ baru juga    ┆ baru juga   ┆ baru juga   ┆ a", "baru", ┆ "pas", …    ┆ "pas", …    ┆ "pas", …    │
│ download …   ┆ download …  ┆ unduh tap…  ┆ … "ya"]     ┆ "bintang"]  ┆ "bintang"]  ┆ "bintang"]  │
│ baguss sih   ┆ baguss sih  ┆ baguss sih  ┆ ["baguss",  ┆ ["baguss",  ┆ ["baguss",  ┆ ["baguss",  │
│ buat         ┆ buat        ┆ buat        ┆ "sih", …    ┆ "belajar",  ┆ "ajar", …   ┆ "belajar",  │
│ belajar,     ┆ belajar,    ┆ belajar,    ┆ "nya"]      ┆ … "kedep…   ┆ "depan"]    ┆ … "kedep…   │
│ mudah…       ┆ mudah…      ┆ mudah…      ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [55]:
df_export = df_comparison.clone()

token_columns = [
    "tokens",
    "tokens_no_stopwords",
    "tokens_stemmed",
    "tokens_lemmatized"
]

# Ubah list token menjadi string
for col in token_columns:
    df_export = df_export.with_columns(
        df_export[col].map_elements(
            lambda tokens: " ".join(tokens) if isinstance(tokens, list) else str(tokens),
            return_dtype=pl.Utf8
        ).alias(col)
    )

# # Simpan hasil ke CSV
# df_export.write_csv(
#     "hasil_preprocessing.csv",
#     encoding="utf8"   # Polars tidak pakai "utf-8-sig", cukup "utf8"
# )

In [57]:
df_export = df_comparison.with_columns(
    [pl.col(c).list.join(" ") for c in token_columns]
)

df_export.write_csv("hasil_preprocessingdatasample.csv")

In [58]:
df_export.write_csv("hasil_preprocessingdatasample.csv")

In [59]:
df_load = pl.read_csv('hasil_preprocessingdatasample.csv')

In [60]:
df_load

shape: (200, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ text         ┆ text_clean  ┆ text_normal ┆ tokens      ┆ tokens_no_s ┆ tokens_stem ┆ tokens_lemm │
│ ---          ┆ ---         ┆ ized        ┆ ---         ┆ topwords    ┆ med         ┆ atized      │
│ str          ┆ str         ┆ ---         ┆ str         ┆ ---         ┆ ---         ┆ ---         │
│              ┆             ┆ str         ┆             ┆ str         ┆ str         ┆ str         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ Aplikasi     ┆ Aplikasi    ┆ aplikasi    ┆ aplikasi    ┆ aplikasi    ┆ aplikasi    ┆ aplikasi    │
│ cerdas       ┆ cerdas      ┆ cerdas      ┆ cerdas      ┆ cerdas      ┆ cerdas      ┆ cerdas      │
│ ,cepat dan   ┆ ,cepat dan  ┆ ,cepat dan  ┆ cepat dan   ┆ cepat       ┆ cepat       ┆ cepat       │
│ sim…         ┆ sim…        ┆ sim…        ┆ simp…       ┆ simple      ┆ simple      ┆ simple      │
│ aplikasi     ┆ aplikasi    ┆ aplikasi    ┆ aplikasi    ┆ aplikasi    ┆ aplikasi    ┆ aplikasi    │
│ ruang guru   ┆ ruang guru  ┆ ruang guru  ┆ ruang guru  ┆ ruang guru  ┆ ruang guru  ┆ ruang guru  │
│ sangat mem…  ┆ sangat mem… ┆ sangat mem… ┆ sangat mem… ┆ membantu    ┆ bantu       ┆ membantu    │
│ aplikasi nya ┆ aplikasi    ┆ aplikasi    ┆ aplikasi    ┆ aplikasi    ┆ aplikasi    ┆ aplikasi    │
│ jelek tapi   ┆ nya jelek   ┆ nya jelek   ┆ nya jelek   ┆ jelek bong  ┆ jelek bong  ┆ jelek bong  │
│ booong…      ┆ tapi        ┆ tapi bong   ┆ tapi bong   ┆ hayuk teri… ┆ hayuk teri… ┆ hayuk teri… │
│              ┆ booong…     ┆ h…          ┆ h…          ┆             ┆             ┆             │
│ sebenarnya   ┆ sebenarnya  ┆ sebenarnya  ┆ sebenarnya  ┆ unduh pas   ┆ unduh pas   ┆ unduh pas   │
│ baru juga    ┆ baru juga   ┆ baru juga   ┆ baru juga   ┆ menonton    ┆ tonton      ┆ nonton      │
│ download …   ┆ download …  ┆ unduh tap…  ┆ unduh tap…  ┆ video coc   ┆ video coc   ┆ video coc   │
│              ┆             ┆             ┆             ┆ n…          ┆ nam…        ┆ nam…        │
│ baguss sih   ┆ baguss sih  ┆ baguss sih  ┆ baguss sih  ┆ baguss      ┆ baguss ajar ┆ baguss      │
│ buat         ┆ buat        ┆ buat        ┆ buat        ┆ belajar     ┆ mudah paham ┆ belajar     │
│ belajar,     ┆ belajar,    ┆ belajar,    ┆ belajar     ┆ mudah       ┆ suka e…     ┆ mudah       │
│ mudah…       ┆ mudah…      ┆ mudah…      ┆ mudah …     ┆ pahami su…  ┆             ┆ pahami su…  │
│ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           │
│ bagus        ┆ bagus aplik ┆ bagus aplik ┆ bagus       ┆ bagus       ┆ bagus       ┆ bagus       │
│ aplikasinya, ┆ asinya,     ┆ asinya,     ┆ aplikasinya ┆ aplikasinya ┆ aplikasi    ┆ aplikasinya │
│ banyak lati… ┆ banyak      ┆ banyak      ┆ banyak      ┆ latihan     ┆ latih       ┆ latihan     │
│              ┆ lati…       ┆ lati…       ┆ latih…      ┆             ┆             ┆             │
│ hallo saya   ┆ hallo saya  ┆ hallo saya  ┆ hallo saya  ┆ hallo agung ┆ hallo agung ┆ hallo agung │
│ Agung        ┆ Agung       ┆ agung       ┆ agung       ┆ setiawan    ┆ setiawan    ┆ setiawan    │
│ Setiawan     ┆ Setiawan    ┆ setiawan    ┆ setiawan    ┆ prakerja …  ┆ prakerja …  ┆ prakerja …  │
│ dari…        ┆ dari…       ┆ dari…       ┆ dari…       ┆             ┆             ┆             │
│ Bikin        ┆ Bikin       ┆ membuat     ┆ membuat     ┆ belajar     ┆ ajar bahasa ┆ belajar     │
│ belajar      ┆ belajar     ┆ belajar     ┆ belajar     ┆ bahasa      ┆ inggris     ┆ bahasa      │
│ bahasa       ┆ bahasa      ┆ bahasa      ┆ bahasa      ┆ inggris     ┆ asyik       ┆ inggris     │
│ inggris m…   ┆ inggris m…  ┆ inggris…    ┆ inggris…    ┆ asyik       ┆             ┆ asyik       │
│ Mohon diperm ┆ Mohon diper ┆ mohon diper ┆ mohon diper ┆ mohon diper ┆ mohon mudah ┆ mohon diper │
│ udahkan      ┆ mudahkan    ┆ mudahkan    ┆ mudahkan    ┆ mudahkan    ┆ masuk mula  ┆ mudahkan    │
│ untuk masu…  ┆ untuk masu… ┆ untuk masu… ┆ untuk masu… ┆ masukan pe… ┆ cakap t…    ┆ masukan pe… │
│ Thank you    ┆ Thank you   ┆ thank you   ┆ thank you   ┆ thank you   ┆ thank you   ┆ thank you   │
│ for the      ┆ for the     ┆ for the     ┆ for the     ┆ for the     ┆ for the     ┆ for the     │
│ test...      ┆ test...     ┆ test...     ┆ test        ┆ test        ┆ test ajar   ┆ test        │
│ Pela…        ┆ Pela…       ┆ pela…       ┆ pelajar…    ┆ pelajar…    ┆             ┆ pelajar…    │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘